### ISSUE TITLE
creating a tag fails

### ISSUE THREAD

**Issue by damageboy** [gpocentek/python-gitlab#231] opened 2017-03-02 11:48 UTC
```python
gl = gitlab.Gitlab('http://xxx', 'somesecret')
gl.auth()
p = gl.projects.get('zzz/xxx')
tag = p.tags.create({ 'tag_name': 'blah', 'ref': 'master' })
```

returns:
```
Traceback (most recent call last):
  File "gitlab-release.py", line 33, in <module>
    tag = p.tags.create({ 'tag_name': args.tag, 'ref': 'master' })
  File "C:\dev\python27\lib\site-packages\gitlab\objects.py", line 144, in create
    return self.obj_cls.create(self.gitlab, data, **args)
  File "C:\dev\python27\lib\site-packages\gitlab\objects.py", line 358, in create
    obj.save()
  File "C:\dev\python27\lib\site-packages\gitlab\objects.py", line 328, in save
    self._create(**kwargs)
  File "C:\dev\python27\lib\site-packages\gitlab\objects.py", line 313, in _create
    json = self.gitlab.create(self, **kwargs)
  File "C:\dev\python27\lib\site-packages\gitlab\__init__.py", line 513, in create
    raise_error_from_response(r, GitlabCreateError, 201)
  File "C:\dev\python27\lib\site-packages\gitlab\exceptions.py", line 180, in raise_error_from_response
    response_body=response.content)
gitlab.exceptions.GitlabCreateError: 200: []
```

**Comment by gpocentek** [comment] 2017-03-03 12:46
Looks like you are using an older version of gitlab, which returns the wrong error code. Your tag has probably been created.
What is your gitlab server version?

**Comment by damageboy** [comment] 2017-03-05 08:35
nope. gitlab-8.17.1-ce

also ran the gitlab checks etc.

**Comment by gpocentek** [comment] 2017-03-05 10:24
I've not been able to reproduce the problem with gitlab-8.17.2-ce and nothing in the gitlab changelog suggests that they fixed something broken in 8.17.1:

`````python
>>> p.tags.create({'tag_name': 'bar', 'ref': 'master'})
<ProjectTag name:bar>
>>> p.tags.list()
[<ProjectTag name:foo>, <ProjectTag name:bar>]
`````

From the trace it seems that gitlab returns a 200 code, which is surprising. Could you enable debug to make sure we send the proper query (``gl.enable_debug()``)? Thanks.

**Comment by gpocentek** [comment] 2017-05-20 08:07
@damageboy I'm closing this issue since I didn't get feedback. Feel free to reopen.

**Closed by gpocentek** 2017-05-20 08:07 UTC
Labels: need info

**Comment by fmauch** [comment] 2017-07-19 13:05
I'm currently having the same issues. With debugging enabled I get

```
send: 'POST /api/v3/projects/473/repository/tags HTTP/1.1\r\nHost: <my_host>\r\nConnection: keep-alive\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: python-requests/2.11.1\r\nPRIVATE-TOKEN: <my_token>\r\nContent-type: application/json\r\nContent-Length: 36\r\n\r\n{"tag_name": "foo", "ref": "master"}'
reply: 'HTTP/1.1 301 Moved Permanently\r\n'
header: Server: nginx
header: Date: Wed, 19 Jul 2017 13:00:17 GMT
header: Content-Type: text/html
header: Content-Length: 178
header: Connection: keep-alive
header: Location: https://<my_host>:443/api/v3/projects/473/repository/tags
DEBUG:requests.packages.urllib3.connectionpool:"POST /api/v3/projects/473/repository/tags HTTP/1.1" 301 178
send: 'GET /api/v3/projects/473/repository/tags HTTP/1.1\r\nHost: <my_host>\r\nConnection: keep-alive\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: python-requests/2.11.1\r\nPRIVATE-TOKEN: <my_token>\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx
header: Date: Wed, 19 Jul 2017 13:00:17 GMT
header: Content-Type: application/json
header: Content-Length: 3723
header: Connection: keep-alive
header: Cache-Control: max-age=0, private, must-revalidate
header: Etag: W/"9638d69b7b6350de2f01995cedbfcc31"
header: Vary: Origin
header: X-Frame-Options: SAMEORIGIN
header: X-Request-Id: 5acc0cbe-a9c0-4cf1-8e4d-4f8313b55c5d
header: X-Runtime: 0.019041
header: Strict-Transport-Security: max-age=31536000
DEBUG:requests.packages.urllib3.connectionpool:"GET /api/v3/projects/473/repository/tags HTTP/1.1" 200 3723
Traceback (most recent call last):
  File "./migrateTags.py", line 86, in <module>
    main()
  File "./migrateTags.py", line 77, in main
    project.tags.create({'tag_name': 'foo', 'ref':'master'})
  File "/home/mauch/Documents/admin/gitlabvgroup/gitlab/base.py", line 139, in create
    return self.obj_cls.create(self.gitlab, data, **args)
  File "/home/mauch/Documents/admin/gitlabvgroup/gitlab/base.py", line 358, in create
    obj.save()
  File "/home/mauch/Documents/admin/gitlabvgroup/gitlab/base.py", line 328, in save
    self._create(**kwargs)
  File "/home/mauch/Documents/admin/gitlabvgroup/gitlab/base.py", line 313, in _create
    json = self.gitlab.create(self, **kwargs)
  File "/home/mauch/Documents/admin/gitlabvgroup/gitlab/__init__.py", line 559, in create
    raise_error_from_response(r, GitlabCreateError, 201)
  File "/home/mauch/Documents/admin/gitlabvgroup/gitlab/exceptions.py", line 204, in raise_error_from_response
    response_body=response.content)
gitlab.exceptions.GitlabCreateError: 200: [<list of all my existing tags>]
```

**Comment by rfletchr** [comment] 2017-11-20 10:06
I just wanted to chime in on this one. I was having exactly the same issue trying to post changes to gitlab.com. I'd naively used a `http` rather than `https` . 
While I was using HTTP i could view my private content but not modify it. All POST commands were being treated as GET commands by the site and would return a 200 Code.  Switching to HTTPS fixed this.

In plain language for other ludites like myself:
use `https://gitlab.com` not `http://gitlab.com`

**Comment by damageboy** [comment] 2017-11-20 11:39
Thanks!
