### ISSUE TITLE
Docs incorrect?

### ISSUE THREAD

**Issue by mainderay** [gpocentek/python-gitlab#232] opened 2017-03-09 20:21 UTC
Greetings. Running 0.19 API and using the docs (stable or latest) and in this page:

http://python-gitlab.readthedocs.io/en/latest/gl_objects/projects.html

it has this section:

> Create a project in a group:
> 
> You need to get the id of the group, then use the namespace_id attribute to create the group:
> 
> ```
> group_id = gl.groups.search('my-group')[0].id
> project = gl.projects.create({'name': 'myrepo', 'namespace_id': group_id})
> ```

that shows 'namespace_id' as the parameter name. I kept getting a namespace error so I tried using the CLI and happened to notice the help therein had the parameter listed as 'namespace-id' (with a dash instead of an underscore) instead. I tried this in my code and it resolved the issue!

I hope this helps others. Thank you for a great library!

**Comment by gpocentek** [comment] 2017-03-17 10:37
Hello,

I've not been able to reproduce this problem, ``namespace_id`` works fine for me. Are you using python 2 or 3? On which platform (linux, windows)?

Thanks.

**Comment by mainderay** [comment] 2017-03-18 17:41
Thank for the reply. I should have given more background.

I'm on OSX 10.11.6 (El Capitan) and using an Ansible Module that uses this library (gitlab_project.py). Ansible is making us of Python 2.7.10. The Ansible module was using pyapi-gitlab, but is moving to using this library instead for various reasons.

I'll see if I can put together a code sample to reproduce the issue and post it. Thank you for looking at it and apologies for the weak background on the initial comment.

**Comment by mainderay** [comment] 2017-03-19 03:44
Ok. Here is a terminal session based on the docs. Notice the first attempt has an underscore (namespace_id) and fails with an 'invalid' message. We then try again with a dash (namespace-id) and it works. I double-checked and indeed the new repo has been created in my Gitlab account.

```
raymond ~ $ python3
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gitlab
>>> gl = gitlab.Gitlab('https://gitlab.com', 'gitlab private token here')
>>> project = gl.projects.create({'name': 'myrepo', 'namespace_id': 'watusee'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gitlab/objects.py", line 144, in create
    return self.obj_cls.create(self.gitlab, data, **args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gitlab/objects.py", line 358, in create
    obj.save()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gitlab/objects.py", line 328, in save
    self._create(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gitlab/objects.py", line 313, in _create
    json = self.gitlab.create(self, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gitlab/__init__.py", line 513, in create
    raise_error_from_response(r, GitlabCreateError, 201)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gitlab/exceptions.py", line 180, in raise_error_from_response
    response_body=response.content)
gitlab.exceptions.GitlabCreateError: 400: b'{"error":"namespace_id is invalid"}'
>>> project = gl.projects.create({'name': 'myrepo', 'namespace-id': 'watusee'})
>>>
```

**Comment by mainderay** [comment] 2017-03-19 03:45
I should also add that I'm having trouble with Python 2.7.13 and 2.7.10. I'll open a separate issue for these.

**Comment by gpocentek** [comment] 2017-03-19 07:21
The namespace_id attribute must be an int, not a string (it's the group ID).

The ``namespace-id`` attribute is ignored so the project you created belongs to your currently logged-in user namespace, not to the group namespace.

**Comment by gpocentek** [comment] 2017-05-20 08:07
@mainderay I'm closing this issue since I didn't get more feedback. Feel free to reopen.

**Closed by gpocentek** 2017-05-20 08:07 UTC
Labels: need info
