### ISSUE TITLE
Could not connect to GitLab

### ISSUE THREAD

**Issue by atigerwei** [gpocentek/python-gitlab#52] opened 2015-01-17 07:14 UTC
Hi,

My Gitlab version is GitLab 7.0.0 de9bf7d, I have installed the python-gitlab, but it can not connect to GitLab:

>gitlab user list          
Could not connect to GitLab (https://mydomain/api/v3)

I can capture the request from the Gitlab server with tcpdump.
How can I know the reason?

Thanks in advance.

**Comment by gpocentek** [comment] 2015-01-19 07:04
There's no easy way to detect what the problem is using the command line at the moment. Check that you can reach the server (test with something like ``curl https://mydomain/api/v3``, and check that the auth token set in the configuration file is correct.

**Comment by atigerwei** [comment] 2015-01-20 08:12
Auth token is correct, I can use the following command to get the user list:
curl -s -k -H "PRIVATE-TOKEN: xxxxxxxxxxxxxxxxxxxxxxxxxx" -H 'Accept: application/json' -H 'Content-Type: application/json' https://mydomain/api/v3/user

Any more suggestions?

Thanks

**Comment by gpocentek** [comment] 2015-01-20 14:43
Since you use -k in your curl command, make sure that ``ssl_verify = False`` is set in your config file.

**Comment by atigerwei** [comment] 2015-01-21 02:43
My  config file is as follow:
[global]
default = local
ssl_verify = true

[local]
url = https://mydomain/api/v3
private_token = xxxxxxxxxxxxxxxxxxxx

[distant]
url = https://mydomain2/api/v3
private_token = yyyyyyyyyyyyyyyyyyy
ssl_verify = false

**Comment by gpocentek** [comment] 2015-01-21 08:26
From your config and your previous samples, the [local] section needs ``ssl_verify = false``.

**Comment by atigerwei** [comment] 2015-01-21 14:00
It still cannot connect to gitlab after setting the ssl_verify = false in configration file.

The output of the command line are as fllows:
/usr/local/lib/python2.7/dist-packages/requests-2.5.1-py2.7.egg/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

Need more modules for gitlab?

**Comment by gpocentek** [comment] 2015-09-19 09:29
Have you managed to connect to gitlab with python-gitlab?

**Comment by gpocentek** [comment] 2016-01-30 16:49
No more feedback so I'm closing this issue. Feel free to reopen.

**Closed by gpocentek** 2016-01-30 16:49 UTC
