### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by BrickXu** [gpocentek/python-gitlab#214] opened 2017-02-06 06:59 UTC
`group.projects` is a list object, not gitlab object and has no method named `list`.

------
In page: gl_objects/groups.rst

**Comment by gpocentek** [comment] 2017-02-06 07:04
Thanks for your feedback. This is actually a bug in the Group class.

Duplicate of #209

**Comment by gpocentek** [comment] 2017-03-17 16:44
#209 has been closed, closing this issue also.

**Closed by gpocentek** 2017-03-17 16:44 UTC
