### ISSUE TITLE
can_create_group reversed when creating user

### ISSUE THREAD

**Issue by marcolefo** [gpocentek/python-gitlab#21] opened 2014-02-21 09:49 UTC
Hello

It seems that can_create_group is reversed. If can_create_group is True, the user can not create group :)

``` shell
# python
Python 2.7.3 (default, Jan  2 2013, 13:56:14) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gitlab
>>> gl = gitlab.Gitlab("http://gitlab.domain/gitlab","admin_token")
>>> gl.auth()
>>> u=gl.User({"username": "john", "email": "john@youpi.fr", "name": "John", "password": "toto12345", "projects_limit": 10, "admin": False, "can_create_group": False})
>>> u.save()
>>> print u.can_create_group
True
>>> j=gl.User({"username": "john1", "email": "john1@youpi.fr", "name": "John1", "password": "toto12345", "projects_limit": 10, "admin": False, "can_create_group": True})
>>> j.save()
>>> print j.can_create_group
None
```

**Comment by pa4373** [comment] 2015-09-24 08:29
I'm guessing that it's the same problem as 'confirm' field. While it's actually the issue of GitLab HQ, maybe we can implictly convert all boolean value to boolean string in `_data_for_gitlab`?

**Comment by gpocentek** [comment] 2016-11-06 06:48
This was a long long time ago but I just retested and using boolean works as expected. To be honest I'm not sure if it was a problem with python-gitlab or GitLab itself. Since the behavior seems correct now I'll close this issue. Feel free to reopen if you can still reproduce.

**Closed by gpocentek** 2016-11-06 06:48 UTC
